<Project>

  <PropertyGroup>
    <!-- See https://www.nuget.org/packages/JetBrains.ReSharper.SDK -->
    <!-- Keep in sync with ProductVersion in gradle.properties -->
    <SdkVersion>2026.1</SdkVersion>

    <Title>Field Assignment Generator</Title>
    <Description>Field Assignment Generator plugin generates field assignments for C++ structs and classes from code completion</Description>

    <Authors>yaetoti</Authors>
    <Copyright>Copyright $([System.DateTime]::Now.Year) yaetoti</Copyright>
    <PackageTags>resharper plugin</PackageTags>

    <PackageProjectUrl></PackageProjectUrl>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageIconUrl></PackageIconUrl>
  </PropertyGroup>

</Project>
