//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: FieldAssignmentGeneratorModel.kt:8</p>
  /// </summary>
  [JetBrains.Application.ShellComponent(Application.Parts.Instantiation.DemandAnyThreadSafe)]
  public class FieldAssignmentGeneratorModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<bool> IsTestRunning => _IsTestRunning;
    [NotNull] public ISignal<string> TestFrameworkDetected => _TestFrameworkDetected;
    [NotNull] public IRdEndpoint<string, string> GetTestExecutionCommand => _GetTestExecutionCommand;
    
    //private fields
    [NotNull] private readonly RdProperty<bool> _IsTestRunning;
    [NotNull] private readonly RdSignal<string> _TestFrameworkDetected;
    [NotNull] private readonly RdCall<string, string> _GetTestExecutionCommand;
    
    //primary constructor
    private FieldAssignmentGeneratorModel(
      [NotNull] RdProperty<bool> isTestRunning,
      [NotNull] RdSignal<string> testFrameworkDetected,
      [NotNull] RdCall<string, string> getTestExecutionCommand
    )
    {
      if (isTestRunning == null) throw new ArgumentNullException("isTestRunning");
      if (testFrameworkDetected == null) throw new ArgumentNullException("testFrameworkDetected");
      if (getTestExecutionCommand == null) throw new ArgumentNullException("getTestExecutionCommand");
      
      _IsTestRunning = isTestRunning;
      _TestFrameworkDetected = testFrameworkDetected;
      _GetTestExecutionCommand = getTestExecutionCommand;
      _IsTestRunning.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("isTestRunning", _IsTestRunning));
      BindableChildren.Add(new KeyValuePair<string, object>("testFrameworkDetected", _TestFrameworkDetected));
      BindableChildren.Add(new KeyValuePair<string, object>("getTestExecutionCommand", _GetTestExecutionCommand));
    }
    //secondary constructor
    private FieldAssignmentGeneratorModel (
    ) : this (
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdSignal<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdCall<string, string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => 3080693468605619276L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    public FieldAssignmentGeneratorModel(Lifetime lifetime, IProtocol protocol) : this()
    {
      Identify(protocol.Identities, RdId.Root.Mix("FieldAssignmentGeneratorModel"));
      this.BindTopLevel(lifetime, protocol, "FieldAssignmentGeneratorModel");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("FieldAssignmentGeneratorModel (");
      using (printer.IndentCookie()) {
        printer.Print("isTestRunning = "); _IsTestRunning.PrintEx(printer); printer.Println();
        printer.Print("testFrameworkDetected = "); _TestFrameworkDetected.PrintEx(printer); printer.Println();
        printer.Print("getTestExecutionCommand = "); _GetTestExecutionCommand.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
